"""Submission factory contracts for database-ready OME-TIFF batches."""

from .manifests import SubmissionManifest, load_submission_manifest
from .models import (
    DetectedTissueSection,
    OutputDerivative,
    PhysicalBoundingBox,
    PixelBoundingBox,
    SourceSlide,
    SubmissionBatch,
)
from .preflight import (
    IssueSeverity,
    PreflightIssue,
    PreflightReport,
    PreflightRowResult,
    PreflightRunResult,
    PreflightState,
    PreflightStateIssue,
    PreflightStateRow,
    run_preflight,
)
from .profiles import DatabaseProfile, RequirementPhase, load_database_profile
from .statuses import (
    BatchStatus,
    ReviewDecision,
    TissuePlanRowCategory,
    TissuePlanStatus,
    TissueStatus,
)
from .tissue_plan import (
    TISSUE_PLAN_VERSION,
    TissueDetectionPlan,
    TissuePlanError,
    TissuePlanJob,
    TissuePlanJobInputs,
    TissuePlanJobOutputs,
    TissuePlanRowSummary,
    TissuePlanRunResult,
    build_tissue_detection_plan,
    load_preflight_state,
    plan_tissues_from_state,
)
from .validation import ManifestValidationError, ProfileValidationError, SubmissionValidationError

__all__ = [
    "BatchStatus",
    "DatabaseProfile",
    "DetectedTissueSection",
    "IssueSeverity",
    "ManifestValidationError",
    "OutputDerivative",
    "PhysicalBoundingBox",
    "PixelBoundingBox",
    "PreflightIssue",
    "PreflightReport",
    "PreflightRunResult",
    "PreflightState",
    "PreflightStateIssue",
    "PreflightStateRow",
    "PreflightRowResult",
    "ProfileValidationError",
    "RequirementPhase",
    "ReviewDecision",
    "SourceSlide",
    "SubmissionBatch",
    "SubmissionManifest",
    "SubmissionValidationError",
    "TissuePlanRowCategory",
    "TissuePlanStatus",
    "TISSUE_PLAN_VERSION",
    "TissueDetectionPlan",
    "TissuePlanError",
    "TissuePlanJob",
    "TissuePlanJobInputs",
    "TissuePlanJobOutputs",
    "TissuePlanRowSummary",
    "TissuePlanRunResult",
    "TissueStatus",
    "load_database_profile",
    "load_submission_manifest",
    "build_tissue_detection_plan",
    "load_preflight_state",
    "plan_tissues_from_state",
    "run_preflight",
]
