#!/bin/bash
# ============================================
# WSI Tissue Pipeline - MLflow Setup Script
# ============================================
# Sets up MLflow tracking for experiment management.
# Can be used with local SQLite, file store, or remote server.

set -e

# Default values
TRACKING_URI="${MLFLOW_TRACKING_URI:-sqlite:///mlflow.db}"
EXPERIMENT_NAME="${MLFLOW_EXPERIMENT_NAME:-wsi-tissue-pipeline}"
ARTIFACTS_DIR="${MLFLOW_ARTIFACTS_DIR:-./mlruns}"
HOST="${MLFLOW_HOST:-127.0.0.1}"
PORT="${MLFLOW_PORT:-5000}"
BACKEND_STORE="sqlite"
MODE="local"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_banner() {
    echo -e "${BLUE}"
    echo "============================================"
    echo "  WSI Tissue Pipeline - MLflow Setup"
    echo "============================================"
    echo -e "${NC}"
}

print_usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Options:
    --mode MODE         Setup mode: local, server, or docker (default: local)
    --tracking-uri URI  MLflow tracking URI (default: sqlite:///mlflow.db)
    --experiment NAME   Experiment name (default: wsi-tissue-pipeline)
    --artifacts DIR     Artifacts directory (default: ./mlruns)
    --host HOST         Server host (default: 127.0.0.1)
    --port PORT         Server port (default: 5000)
    --help              Show this help message

Modes:
    local   - Use local SQLite database (single user)
    server  - Start MLflow tracking server (multi-user)
    docker  - Configure for Docker Compose setup

Examples:
    # Basic local setup
    $0

    # Start tracking server
    $0 --mode server --port 5000

    # Configure for Colab with Google Drive storage
    $0 --tracking-uri "sqlite:////content/drive/MyDrive/mlflow.db" \\
       --artifacts "/content/drive/MyDrive/mlruns"

    # Docker setup
    $0 --mode docker
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --mode)
            MODE="$2"
            shift 2
            ;;
        --tracking-uri)
            TRACKING_URI="$2"
            shift 2
            ;;
        --experiment)
            EXPERIMENT_NAME="$2"
            shift 2
            ;;
        --artifacts)
            ARTIFACTS_DIR="$2"
            shift 2
            ;;
        --host)
            HOST="$2"
            shift 2
            ;;
        --port)
            PORT="$2"
            shift 2
            ;;
        --help)
            print_usage
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            print_usage
            exit 1
            ;;
    esac
done

print_banner

# Check if mlflow is installed
check_mlflow() {
    if ! command -v mlflow &> /dev/null; then
        echo -e "${RED}Error: MLflow is not installed.${NC}"
        echo "Install with: pip install mlflow"
        exit 1
    fi
    echo -e "${GREEN}✓ MLflow version: $(mlflow --version)${NC}"
}

# Setup local SQLite tracking
setup_local() {
    echo -e "${YELLOW}Setting up local MLflow tracking...${NC}"
    
    # Create artifacts directory
    mkdir -p "$ARTIFACTS_DIR"
    
    # Extract database path from URI
    if [[ "$TRACKING_URI" == sqlite:///* ]]; then
        DB_PATH="${TRACKING_URI#sqlite:///}"
        DB_DIR=$(dirname "$DB_PATH")
        if [[ -n "$DB_DIR" && "$DB_DIR" != "." ]]; then
            mkdir -p "$DB_DIR"
        fi
    fi
    
    # Set environment variables
    export MLFLOW_TRACKING_URI="$TRACKING_URI"
    export MLFLOW_EXPERIMENT_NAME="$EXPERIMENT_NAME"
    
    # Create experiment if it doesn't exist
    echo -e "${BLUE}Creating experiment: $EXPERIMENT_NAME${NC}"
    python3 << EOF
import mlflow
mlflow.set_tracking_uri("$TRACKING_URI")
try:
    mlflow.create_experiment("$EXPERIMENT_NAME", artifact_location="$ARTIFACTS_DIR")
    print("Created new experiment")
except mlflow.exceptions.MlflowException:
    print("Experiment already exists")
mlflow.set_experiment("$EXPERIMENT_NAME")
print(f"Experiment ID: {mlflow.get_experiment_by_name('$EXPERIMENT_NAME').experiment_id}")
EOF
    
    # Create .env file
    cat > .env.mlflow << EOF
# MLflow Configuration
# Generated by setup_mlflow.sh on $(date)
MLFLOW_TRACKING_URI=$TRACKING_URI
MLFLOW_EXPERIMENT_NAME=$EXPERIMENT_NAME
MLFLOW_ARTIFACTS_DIR=$ARTIFACTS_DIR
EOF
    
    echo -e "${GREEN}✓ Local MLflow setup complete${NC}"
    echo -e "${BLUE}Configuration saved to .env.mlflow${NC}"
}

# Start MLflow tracking server
setup_server() {
    echo -e "${YELLOW}Starting MLflow tracking server...${NC}"
    
    # Create directories
    mkdir -p "$ARTIFACTS_DIR"
    
    # Extract database path
    if [[ "$TRACKING_URI" == sqlite:///* ]]; then
        DB_PATH="${TRACKING_URI#sqlite:///}"
        DB_DIR=$(dirname "$DB_PATH")
        if [[ -n "$DB_DIR" && "$DB_DIR" != "." ]]; then
            mkdir -p "$DB_DIR"
        fi
    fi
    
    echo -e "${BLUE}Server configuration:${NC}"
    echo "  Host: $HOST"
    echo "  Port: $PORT"
    echo "  Backend store: $TRACKING_URI"
    echo "  Artifact store: $ARTIFACTS_DIR"
    echo ""
    echo -e "${YELLOW}Starting server (Ctrl+C to stop)...${NC}"
    echo ""
    
    mlflow server \
        --backend-store-uri "$TRACKING_URI" \
        --default-artifact-root "$ARTIFACTS_DIR" \
        --host "$HOST" \
        --port "$PORT"
}

# Configure for Docker
setup_docker() {
    echo -e "${YELLOW}Configuring MLflow for Docker...${NC}"
    
    # Create environment file for docker-compose
    cat > docker/.env << EOF
# MLflow Docker Configuration
# Generated by setup_mlflow.sh on $(date)
MLFLOW_TRACKING_URI=http://mlflow:5000
MLFLOW_EXPERIMENT_NAME=$EXPERIMENT_NAME
POSTGRES_USER=mlflow
POSTGRES_PASSWORD=mlflow_password
POSTGRES_DB=mlflow
EOF
    
    echo -e "${GREEN}✓ Docker configuration saved to docker/.env${NC}"
    echo ""
    echo -e "${BLUE}To start MLflow with Docker Compose:${NC}"
    echo "  cd docker"
    echo "  docker-compose up -d mlflow"
    echo ""
    echo -e "${BLUE}MLflow UI will be available at: http://localhost:5000${NC}"
}

# Main execution
check_mlflow

case "$MODE" in
    local)
        setup_local
        echo ""
        echo -e "${BLUE}To use MLflow in your scripts:${NC}"
        echo "  source .env.mlflow"
        echo "  python run_pipeline.py --input data/ --output results/"
        ;;
    server)
        setup_local
        setup_server
        ;;
    docker)
        setup_docker
        ;;
    *)
        echo -e "${RED}Unknown mode: $MODE${NC}"
        print_usage
        exit 1
        ;;
esac

echo ""
echo -e "${GREEN}Done!${NC}"
